# General Jekyll Config
pygments: true
url: http://blog.erikstromlund.com
lsi: false
exclude: [LICENSE, CNAME, README.md, .gitignore]

permalink: none
markdown: redcarpet

# Logam Theme customization
theme:
  # Color for top bar, links, etc
  highlight_color: '#3c7bda'

  # Profile links on the left sidebar, leave blank to ignore
  social:
    github: estromlund
    #bitbucket:
    #hacker_news: estromlund
    #stackexchange:
    #stackoverflow:
    twitter: estromlund
    #facebook:
    #tumblr:
    linkedin: erikstromlund
    gplus: 109948612470574037781

  # "Hi, I'm _______"
  name: Erik Stromlund
  email: erik@erikstromlund.com

  # Google Analytics key, leave blank to ignore
  google_analytics_key: UA-26994379-1

  # Toggle "Postings are my own" disclaimer in footer
  show_disclaimer: false
